### PR TITLE
Feature: update bind and export renderShape

### LINKED ISSUE #8: isPointInPath usage
Drawing with graphics-ts is great! However, I have a use case where I need to handle clicks and check if they are contained in a closed Shape. It looks like the Canvas part of the library includes a method for checking if a point is in a path, but I'm failing to see how to watch for events that land coordinates in a path.

Right now I'm considering writing a Closed Path to Canvas Path combinator and using isPointInPath to manually check for a click imperatively. Any advice would be super helpful. Thanks!

### PR DESCRIPTION
**Pull request by IMax153**
Closes #8.

This PR updates the signature of `bind` in the `Canvas` module to allow for piping `bind` in the `Render` context. In addition, it makes the `renderShape` combinator of the `Drawing` module public.

I also updated the structure of all modules to follow the convention in `fp-ts`, added `category` tags to all exports, and updated the documentation accordingly. See changes below.

# 1.1.0

- **Breaking Change**

  - upgrade to latest `fp-ts` (2.7.0), latest `fp-ts-contrib` (0.1.17), and latest TypeScript (3.9.6) (@IMax153)
  - update signature of `bind` in `Canvas` to return a `Render` effect (@IMax153)
  - remove `Handler` type from `Canvas` (@IMax153)

- **New Feature**

  - export `renderShape` from `Drawing` (@IMax153)

- **Polish**

  - upgrade to latest `docs-ts` (0.5.1) and add `category` tags to all module exports (@IMax153)
  - reorganize module structure to follow current convention in `fp-ts` (@IMax153)

### CODE REVIEW

**Review by gcanti — CHANGES_REQUESTED** [review]
> Breaking Change...

@IMax153 are these breaking changes strictly necessary? Since `graphics-ts` hit version `1.0.0` we should strive for backward compatibility

**Comment by IMax153** [comment]
> are these breaking changes strictly necessary? 

Hmm. I don't think that the upgrades to `fp-ts`, `fp-ts-contrib`, or `typescript` are strictly necessary at this time, so those can be reverted if we want to avoid any breaking changes at this time.

As for the changes to `bind`, I think it depends on how we address #8. I think there are a few options.

1. We say that users should bind all event handlers prior to running their `Render` effects
    - **Pros**: We can revert the changes made to `bind` entirely. 
    - **Cons**:  The current implementation of the `bind` function runs in the `Html` context. I think there are many situations in which users will want access to the `Render` context when binding their event handlers. For example, for the situation presented in #8, I had a **much** harder time utilizing the `isPointInPath` combinator within the `Html` context without another call to `renderTo` (which just seemed cumbersome).

2. We add a second version of `bind` (e.g. `bindR`, with a better name...)
    - **Pros**: Allows users the flexibility of binding event handlers within the `Render` context
    - **Cons**: Creates a (sort-of) duplication of the `bind` logic and may be somewhat confusing to users

3. We make the breaking change given that we know users are reaching for `bind` in the `Render` context (i.e. #8)
    - **Pros**: Same as 2 with additional benefit of not adding a second version of `bind`
    - **Cons**: It is a breaking change and some users may be using `bind` in the `Html` context. However, this seems unlikely as we already have one user demonstrating their confusion with the current implementation of `bind`.

**Comment by gcanti** [comment]
> I don't think that the upgrades to fp-ts, fp-ts-contrib, or typescript are strictly necessary at this time, so those can be reverted if we want to avoid any breaking changes at this time.

:+1:

> However, this seems unlikely

I agree but, even if it's unlikely, if we make any breaking change we must bump the major version to `2.0.0`.

We could postpone any breaking change until fp-ts v3 comes out, so I'd to go for option 2 (`bindWithContext`?).

Optionally, if you think that the old `bind` is really useless, you could deprecate it (i.e. adding a `@deprecated` tag) in favour of the new API.

**Comment by IMax153** [comment]
> I agree but, even if it's unlikely, if we make any breaking change we must bump the major version to `2.0.0`.

Makes sense - I will make sure to be more aware of the impact of breaking changes when addressing issues and making updates in the future.

> We could postpone any breaking change until fp-ts v3 comes out, so I'd to go for option 2 (`bindWithContext`?).

I agree, if we are postponing any breaking changes then I think this is the best option to ensure that #8 is adequately addressed 👍. `bindWithContext` seems reasonable enough.

> adding a `@deprecated` tag

I like this idea as well - I went ahead and added `@deprecated` tags to the `bind` combinator and the `Handler` type. In addition, I added a `TODO` to remove in version `2.0.0` of `graphics-ts` and rename `bindWithContext` to `bind`.

So the changes contained within this PR can be summarized as follows.

# 1.1.0

- **New Feature**

  - add `bindWithContext` to `Canvas` module (@IMax153)
  - export `renderShape` from `Drawing` (@IMax153)

- **Polish**

  - deprecate `bind` and `Handler` in `Canvas` module (@IMax153)
  - reorganize module structure to follow current convention in `fp-ts` (@IMax153)

- **Documentation**

  - upgrade to latest `docs-ts` (0.5.1) and add `category` tags to all module exports (@IMax153)

**Review by gcanti — APPROVED** [review]

**Comment by gcanti** [comment]
Nice, thank you. Going to merge

**Pull request merged**
